### ISSUE TITLE
Unable to resolve action `google-github-actions/setup-gcloud@master`, unable to find version `master`

### ISSUE THREAD

**Issue by jsakas** [google-github-actions/setup-gcloud#453] opened 2021-12-22 18:56 UTC
### TL;DR

We just started receiving this error, is it expected?

```
Error: Unable to resolve action `google-github-actions/setup-gcloud@master`, unable to find version `master`
```

Our setup:

```
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
```

### Action YAML

```yaml
- name: Setup GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
```
```


### Additional information

_No response_

**Comment by sethvargo** [comment] 2021-12-22 18:58
Duplicate of #451. We renamed the branch to `main`, but despite [GitHub's blog post](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/), this broke existing workflows. We re-renamed the branch back to `master` and workflows should work again now. Sorry about that.

**Closed by sethvargo** 2021-12-22 18:58 UTC
Labels: bug
