### ISSUE TITLE
Support gcloud alpha / beta

### ISSUE THREAD

**Issue by ocervell** [google-github-actions/setup-gcloud#330] opened 2021-06-24 14:03 UTC
Currently, I have to run `gcloud components update` in order to run `gcloud alpha` and `gcloud beta` commands. Maybe we could add a flag to automatically get those ?

**Comment by bharathkkb** [comment] 2021-06-30 00:35
@ocervell 👋 
We are looking into supporting this soon. /cc @averikitsch

**Comment by erzz** [comment] 2021-09-21 06:45
any update?

**Comment by sethvargo** [comment] 2021-11-30 21:32
Duplicate of https://github.com/google-github-actions/setup-gcloud/issues/103

**Closed by sethvargo** 2021-11-30 21:32 UTC
Labels: feature
