### ISSUE TITLE
Expand-Archive ... not a supported archive file format

### ISSUE THREAD

**Issue by uportalis** [google-github-actions/setup-gcloud#429] opened 2021-12-08 17:09 UTC
### TL;DR

I get the following error when using setup-gcloud action on self-hosted runners on Windows 10:

```
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
```

### Expected behavior

No error.

### Observed behavior

Error:

```
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'D:\actions-runner\_work\_temp\ab4df221-584f-41c1-83db-67d81e518f23' -DestinationPath 'D:\actions-runner\_work\_temp\b3bd1032-a3fb-48d8-b7a7-ce30839ebd81' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('D:\actions-runner\_work\_temp\ab4df221-584f-41c1-83db-67d81e518f23', 'D:\actions-runner\_work\_temp\b3bd1032-a3fb-48d8-b7a7-ce30839ebd81', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'D:\actions-runner\_work\_tem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
 
Error: google-github-actions/setup-gcloud failed with: The process 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

### Action YAML

```yaml
- name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.MY_EMAIL }}
          service_account_key: ${{ secrets.MY_KEY }}
```

### Additional information

Windows 10 is supposed to be supported for GitHub Actions (see https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners).

Here are details of my Windows 10 runner:

```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Administrator> systeminfo

Host Name:                 HOSTNAME02
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Admin
Registered Organization:
Product ID:                00330-80000-00000-AA412
Original Install Date:     03/05/2021, 11:13:42
System Boot Time:          18/11/2021, 07:34:52
System Manufacturer:       VMware, Inc.
System Model:              VMware7,1
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 49 Stepping 0 AuthenticAMD ~2795 Mhz
BIOS Version:              VMware, Inc. VMW71.00V.13989454.B64.1906190538, 19/06/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              fr-ch;French (Switzerland)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     8.191 MB
Available Physical Memory: 4.106 MB
Virtual Memory: Max Size:  9.471 MB
Virtual Memory: Available: 3.408 MB
Virtual Memory: In Use:    6.063 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\HOSTNAME02
[...]
```

**Comment by sethvargo** [comment] 2021-12-08 17:15
Duplicate of https://github.com/google-github-actions/setup-gcloud/issues/401. Let's centralize there.

**Closed by sethvargo** 2021-12-08 17:15 UTC
Labels: bug
